github: [metadata]
kramdown:
 input: GFM
 hard_wrap: false
permalink: /:title
gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-redirect-from

url: https://sunderb.github.io
#url: http://127.0.0.1:4000 # for local testing
